year = int(input("enter number of years: "))
rate = int ( 3 * 10 ** 8)
secondsinYear = int (365 * 24 *60 ** 2)
distanceperSec = (secondsinYear * rate)
print ("Distance per second is: " ,distanceperSec)
